---
name: Build
on:
  push:
    branches:
      - master  # forall push/merge in master
  pull_request:
    branches:
      - "**"  # forall submitted Pull Requests

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.11.x
          - 4.12.x
          - 4.13.x
          - 4.14.x
          - 5.0.x

    runs-on: ${{ matrix.os }}

    env:
      OPAMWITHTEST: true

    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global init.defaultBranch master

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install --deps-only .

      - name: List installed packages
        run: opam list

      - name: Build locally
        run: opam exec -- make

      - name: Upload the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.ocaml-compiler }}-utop.exe
          path: _build/default/src/top/utop.exe

      - name: Build, test, and install package
        run: |
          opam exec -- make examples
          opam install .

      - name: Test dependants
        run: |
          PACKAGES=`opam list -s --color=never --installable --depends-on utop`
          echo "Dependants:" $PACKAGES
          for PACKAGE in $PACKAGES
          do
             echo ::group::Build and test $PACKAGE
             DEPS_FAILED=false
             (opam depext $PACKAGE &&
              opam install --deps-only $PACKAGE) || DEPS_FAILED=true
             [ $DEPS_FAILED == false ] && opam install $PACKAGE
             echo ::endgroup::
             [ $DEPS_FAILED == false ] || echo Dependencies broken
          done

      - name: Uninstall package
        run: opam uninstall .
